---
- name: Add Grafana GPG key
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/grafana-archive-keyring.gpg

- name: Add Grafana repository
  become: true
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    filename: 'grafana'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Grafana package
  become: true
  apt:
    name: grafana
    state: present

- name: Start and enable Grafana service
  become: true
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Ensure Grafana key directory exists
  file:
    path: "/etc/opt/oci-hpc/passwords/grafana"
    state: directory
  delegate_to: localhost

- name: Check Grafana API key list
  uri:
    url: "{{ grafana_api_url }}/api/auth/keys"
    method: GET
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    return_content: true
  no_log: false
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Create Prometheus datasource in Grafana
  grafana_datasource:
    name: "Prometheus"
    grafana_url: "{{ grafana_api_url }}"
    grafana_user: "{{ grafana_security.admin_user }}"
    grafana_password: "{{ grafana_security.admin_password }}"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
  ignore_errors: yes
